#!/usr/bin/env python3
"""Export AirSim camera frames into Dedalus recorded-frame fixtures.

This bridge keeps the C++ core stack dependency-free. It uses the AirSim
Python API in the simulation environment, writes PPM frames plus a manifest,
and the C++ core stack consumes the output through RecordedFrameSource:

    python simulation/airsim/scripts/export-airsim-frames.py --count 5 --output out/airsim_frames
    ./build/apps/dedalus_core_stack --config out/airsim_frames/core_stack_airsim_recorded.yaml

The generated config uses frame_source=recorded_frames and ego_provider=no_telemetry.
A later AirSim C++/IPC backend can replace this bridge behind the same provider
contracts.
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path
from typing import Iterable

import airsim


def ppm_bytes_from_airsim_response(response: object) -> bytes:
    width = int(response.width)
    height = int(response.height)
    raw = bytes(response.image_data_uint8)

    if width <= 0 or height <= 0:
        raise RuntimeError(f"invalid AirSim image dimensions: {width}x{height}")

    pixel_count = width * height
    if len(raw) == pixel_count * 3:
        rgb = raw
    elif len(raw) == pixel_count * 4:
        # AirSim commonly returns BGRA/RGBA-like 4-channel buffers depending on
        # backend. For the bridge, preserve the first three channels as a stable
        # RGB-ish test/debug image and drop alpha.
        rgb = bytearray()
        for i in range(0, len(raw), 4):
            rgb.extend(raw[i : i + 3])
        rgb = bytes(rgb)
    else:
        raise RuntimeError(
            f"unexpected AirSim image byte count: got {len(raw)}, "
            f"expected {pixel_count * 3} or {pixel_count * 4}"
        )

    header = f"P6\n{width} {height}\n255\n".encode("ascii")
    return header + rgb


def write_manifest(path: Path, rows: Iterable[tuple[str, str, int, str]]) -> None:
    with path.open("w", encoding="utf-8") as f:
        f.write("# image_path frame_id timestamp_ns camera_id\n")
        for image_path, frame_id, timestamp_ns, camera_id in rows:
            f.write(f"{image_path} {frame_id} {timestamp_ns} {camera_id}\n")


def write_recorded_config(path: Path, manifest_path: Path, map_frame_id: str) -> None:
    path.write_text(
        "# Generated by simulation/airsim/scripts/export-airsim-frames.py\n"
        "frame_source: recorded_frames\n"
        f"recorded_manifest_path: {manifest_path.as_posix()}\n"
        "ego_provider: no_telemetry\n"
        "detector: scripted\n"
        "tracker: simple_centroid\n"
        "identity_resolver: appearance_only\n"
        "projector: flat_ground\n"
        "world_model: in_memory\n"
        f"fallback_map_frame_id: {map_frame_id}\n",
        encoding="utf-8",
    )


def export_frames(args: argparse.Namespace) -> None:
    output = Path(args.output).expanduser().resolve()
    output.mkdir(parents=True, exist_ok=True)

    client = airsim.MultirotorClient(ip=args.host, port=args.rpc_port)
    client.confirmConnection()

    rows: list[tuple[str, str, int, str]] = []
    metadata: list[dict[str, object]] = []

    for index in range(args.count):
        responses = client.simGetImages(
            [airsim.ImageRequest(args.camera_name, airsim.ImageType.Scene, False, False)],
            vehicle_name=args.vehicle_name,
        )
        if not responses:
            raise RuntimeError("AirSim returned no image responses")

        response = responses[0]
        timestamp_ns = int(getattr(response, "time_stamp", 0) or time.time_ns())
        frame_id = f"airsim_frame_{index + 1:04d}"
        image_name = f"{frame_id}.ppm"
        image_path = output / image_name
        image_path.write_bytes(ppm_bytes_from_airsim_response(response))

        rows.append((image_name, frame_id, timestamp_ns, args.camera_name))
        metadata.append(
            {
                "frame_id": frame_id,
                "timestamp_ns": timestamp_ns,
                "camera_name": args.camera_name,
                "vehicle_name": args.vehicle_name,
                "width": int(response.width),
                "height": int(response.height),
            }
        )

        if args.delay_s > 0 and index + 1 < args.count:
            time.sleep(args.delay_s)

    manifest_path = output / "manifest.txt"
    write_manifest(manifest_path, rows)

    metadata_path = output / "metadata.json"
    metadata_path.write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")

    config_path = output / "core_stack_airsim_recorded.yaml"
    write_recorded_config(config_path, manifest_path, args.map_frame_id)

    print(f"Wrote {len(rows)} AirSim frame(s) to {output}")
    print(f"Manifest: {manifest_path}")
    print(f"Metadata: {metadata_path}")
    print(f"Core-stack config: {config_path}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", default="127.0.0.1", help="AirSim RPC host")
    parser.add_argument("--rpc-port", type=int, default=41451, help="AirSim RPC port")
    parser.add_argument("--vehicle-name", default="PX4", help="AirSim vehicle name")
    parser.add_argument("--camera-name", default="front_center", help="AirSim camera name")
    parser.add_argument("--count", type=int, default=1, help="Number of frames to export")
    parser.add_argument("--delay-s", type=float, default=0.0, help="Delay between captures")
    parser.add_argument("--output", default="out/airsim_frames", help="Output directory")
    parser.add_argument("--map-frame-id", default="map_airsim_recorded_0001")
    return parser.parse_args()


if __name__ == "__main__":
    export_frames(parse_args())
