include: config/world-env/airsim.yaml
include: config/drone/px4_front_center.yaml
include: config/pipeline/visual.yaml
include: config/mission/sequence_far_person.yaml
include: config/output/standard_ppm.yaml

ego_provider: frame_hint

annotation_output_path: out/sequence_far_person_visual_gt_ego_annotation
