#!/usr/bin/env python3
"""Export a Dedalus PPM annotation sequence to MP4 using ffmpeg.

This script intentionally keeps video encoding outside the C++ core stack. It
reads the `manifest.txt` generated by `frame_annotator: ppm_sequence`, verifies
that referenced PPM frames exist, and either prints the ffmpeg command in
`--dry-run` mode or invokes ffmpeg when encoding is requested.
"""

from __future__ import annotations

import argparse
import csv
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class AnnotationRow:
    index: int
    frame_id: str
    timestamp_ns: int
    path: str
    output_fps: float


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export Dedalus ppm_sequence annotation frames to MP4 via ffmpeg."
    )
    parser.add_argument(
        "--annotation-dir",
        required=True,
        type=Path,
        help="Directory containing ppm_sequence manifest.txt and PPM frames.",
    )
    parser.add_argument(
        "--output-mp4",
        required=True,
        type=Path,
        help="MP4 output path to create.",
    )
    parser.add_argument(
        "--fps",
        type=float,
        help="Override output FPS. Defaults to output_fps from annotation manifest.",
    )
    parser.add_argument(
        "--ffmpeg",
        default="ffmpeg",
        help="ffmpeg executable path/name. Default: ffmpeg.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate inputs and print ffmpeg command without requiring/running ffmpeg.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Allow replacing an existing output file.",
    )
    return parser.parse_args()


def fail(message: str) -> None:
    raise AssertionError(message)


def read_manifest(annotation_dir: Path) -> list[AnnotationRow]:
    manifest = annotation_dir / "manifest.txt"
    if not manifest.exists():
        fail(f"missing annotation manifest: {manifest}")

    rows: list[AnnotationRow] = []
    with manifest.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        required = {"frame_index", "frame_id", "timestamp_ns", "path", "output_fps"}
        if set(reader.fieldnames or []) < required:
            fail(f"annotation manifest missing required columns: {manifest}")
        for row in reader:
            rows.append(
                AnnotationRow(
                    index=int(row["frame_index"]),
                    frame_id=row["frame_id"],
                    timestamp_ns=int(row["timestamp_ns"]),
                    path=row["path"],
                    output_fps=float(row["output_fps"]),
                )
            )

    if not rows:
        fail(f"annotation manifest has no rows: {manifest}")
    expected = list(range(1, len(rows) + 1))
    actual = [row.index for row in rows]
    if actual != expected:
        fail(f"annotation frame indices are not contiguous: got {actual}, expected {expected}")
    return rows


def resolve_frame_path(annotation_dir: Path, manifest_value: str) -> Path:
    raw = Path(manifest_value)
    if raw.is_absolute():
        return raw

    candidates = [
        Path.cwd() / raw,
        annotation_dir / raw,
        annotation_dir / raw.name,
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return candidates[0]


def validate_frames(annotation_dir: Path, rows: list[AnnotationRow]) -> list[Path]:
    frame_paths: list[Path] = []
    for row in rows:
        path = resolve_frame_path(annotation_dir, row.path)
        if not path.exists():
            fail(f"missing PPM frame referenced by manifest: {row.path}")
        with path.open("rb") as handle:
            magic = handle.read(2)
        if magic != b"P6":
            fail(f"frame is not P6 PPM: {path}")
        frame_paths.append(path)
    return frame_paths


def manifest_fps(rows: list[AnnotationRow]) -> float:
    fps_values = {row.output_fps for row in rows}
    if len(fps_values) != 1:
        fail(f"annotation manifest has inconsistent output_fps values: {sorted(fps_values)}")
    fps = fps_values.pop()
    if fps <= 0:
        fail(f"annotation FPS must be positive, got {fps}")
    return fps


def build_ffmpeg_command(ffmpeg: str, fps: float, input_pattern: Path, output_mp4: Path, overwrite: bool) -> list[str]:
    command = [
        ffmpeg,
        "-hide_banner",
        "-loglevel",
        "warning",
        "-framerate",
        f"{fps:g}",
        "-i",
        str(input_pattern),
        "-vf",
        "format=yuv420p",
        "-movflags",
        "+faststart",
    ]
    command.append("-y" if overwrite else "-n")
    command.append(str(output_mp4))
    return command


def print_shell_command(command: list[str]) -> None:
    try:
        import shlex

        print(" ".join(shlex.quote(part) for part in command))
    except Exception:
        print(command)


def create_contiguous_links(frame_paths: list[Path], staging_dir: Path) -> Path:
    for index, frame_path in enumerate(frame_paths, start=1):
        target = staging_dir / f"frame_{index:06d}.ppm"
        try:
            target.symlink_to(frame_path.resolve())
        except OSError:
            shutil.copyfile(frame_path, target)
    return staging_dir / "frame_%06d.ppm"


def main() -> int:
    args = parse_args()
    annotation_dir = args.annotation_dir.resolve()
    output_mp4 = args.output_mp4.resolve()

    if not annotation_dir.exists():
        fail(f"annotation directory does not exist: {annotation_dir}")
    if output_mp4.exists() and not args.overwrite and not args.dry_run:
        fail(f"output already exists; pass --overwrite to replace it: {output_mp4}")

    rows = read_manifest(annotation_dir)
    frame_paths = validate_frames(annotation_dir, rows)
    fps = args.fps if args.fps is not None else manifest_fps(rows)
    if fps <= 0:
        fail(f"output FPS must be positive, got {fps}")

    with tempfile.TemporaryDirectory(prefix="dedalus-ppm-mp4-") as temp_dir:
        staging_dir = Path(temp_dir)
        input_pattern = create_contiguous_links(frame_paths, staging_dir)
        command = build_ffmpeg_command(args.ffmpeg, fps, input_pattern, output_mp4, args.overwrite)

        print(f"frames: {len(frame_paths)}")
        print(f"fps: {fps:g}")
        print(f"output: {output_mp4}")
        print("ffmpeg command:")
        print_shell_command(command)

        if args.dry_run:
            print("OK: dry run validated PPM sequence and generated ffmpeg command")
            return 0

        if shutil.which(args.ffmpeg) is None:
            fail(f"ffmpeg executable not found: {args.ffmpeg}; install ffmpeg or use --dry-run")

        output_mp4.parent.mkdir(parents=True, exist_ok=True)
        subprocess.run(command, check=True)
        if not output_mp4.exists() or output_mp4.stat().st_size == 0:
            fail(f"ffmpeg did not create a non-empty output file: {output_mp4}")

    print("OK: MP4 export complete")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except AssertionError as exc:
        print(f"export-ppm-sequence-to-mp4: {exc}", file=sys.stderr)
        raise SystemExit(1)
    except subprocess.CalledProcessError as exc:
        print(f"export-ppm-sequence-to-mp4: ffmpeg failed with exit code {exc.returncode}", file=sys.stderr)
        raise SystemExit(exc.returncode)
